# Generated by Django 3.0.8 on 2020-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswc', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('lyrics', models.TextField(default='')),
                ('duration_in_seconds', models.PositiveSmallIntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('musical_works', models.ManyToManyField(to='musical_works.MusicalWork')),
            ],
        ),
    ]
