# Generated by Django 3.0.8 on 2020-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalwork',
            name='iswc',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
